### ISSUE TITLE
[Bug] "Use Cordials" option in Auto Casts not using HQ Cordial

### ISSUE THREAD

**Issue by DenL** [InitialDet/AutoHook#18]
As title. NQ Cordials can be used no problem, but HQ Cordials are not being used.
Could there also be an option to prioritize lower end cordials before using higher end?
e.g. use up cordials before using hi-cordial

**Comment by InitialDet** [comment]
I'll look into it, I forgot to test the HQ cordials.

I didn't even bother to add a priority because Hi-Cordial is so easy to get and way more time-efficient than Cordials, but ill add an option for it. For now, I recommend placing the Hi-Cordials in your saddlebag if you really don't want to use them.

**Comment by InitialDet** [comment]
Aight HQ Cordials should be fine now
