### ISSUE TITLE
Bug: Thaliak's Favor will be used twice if the option is turned on when Angler's Art stack > 6

### ISSUE THREAD

**Issue by DenL** [InitialDet/AutoHook#29]
If you have >6 stacks, and you turn on the auto Thaliak's Favor when stack >3, the ability will be used twice in a row when GP falls under threshold, wasting the second use.

**Comment by InitialDet** [comment]
Yeah this is an annoying bug, the server takes a "long" time to update the new GP value after Thaliak's Favor is used. So when TF is used the first time, the client still thinks the GP is under the threshold and uses it again.

I'll try to find a good solution, but for now idk how to make it consistent since it depends on the user ping

**Comment by DenL** [comment]
Perhaps some sort of cooldown? Or option to only thaliak's favor once per cast?

**Comment by InitialDet** [comment]
Yeah, not ideal but that could be a band-aid fix ig

**Comment by InitialDet** [comment]
I think I managed to fix it? it might be ping dependent so its not 100%, but it should be fine in most cases.
