### ISSUE TITLE
Greater Area/Bait conditionals

### ISSUE THREAD

**Issue by howlinghart** [InitialDet/AutoHook#45]
Love this addon! Thanks for all your hard work. It would be great to have greater conditionals and reactions and also areas for bait use

An example of this would be:

```
IF in Eastern La Noscea (I don't know if it could go down to say, Rhotano Sea (Privateer Sterncastle)
AND using Northern Krill 
X Rules apply
IF "Little Thalaos" is caught THEN identical Cast. IF Identical Cast is up THEN Double/Triple Hook
IF Intuition THEN use CHUM (Can't currently select chum to be used at specific times)
```

Another great addition would be if chum is used then reduce the given min/max by 30% (or a toggle option for this)

**Comment by InitialDet** [comment]
I went with a manual preset option instead of a conditional based on the current location.
You can manually switch to a X preset when going for Y spot.

> IF "Little Thalaos" is caught THEN identical Cast. IF Identical Cast is up THEN Double/Triple Hook

Create a new preset, Add a fish with the name "Little Thalaos", and enable identical cast
![image](https://user-images.githubusercontent.com/13919114/212237649-2cc4e56f-aab5-4126-94d5-33cef5cf8bbd.png)
![image](https://user-images.githubusercontent.com/13919114/212237369-b81bda28-b4b9-449b-b746-931a6bd760ab.png)
Then select this in the double/triple hook option
![image](https://user-images.githubusercontent.com/13919114/212237423-7d4b297c-4992-45f8-b9de-d1cbdf638c25.png)

>IF Intuition THEN use CHUM

An option to use Chum only when under the effect of Intuition in the Auto Casts tab
