### ISSUE TITLE
Add AutoCast

### ISSUE THREAD

**Issue by Dedoooo** [InitialDet/AutoHook#7]
first time trying this today, its pretty neat. would definitely be nicer with auto cast!

**Comment by InitialDet** [comment]
I tried to avoid going full automation, that's why I didn't implement it. My idea was always having the player interact with the game using Cast/Mooch and not just going full afk. 

That being said you can already do that using triggernometry with some simple triggers, so I might add it to the plugin in the future

**Comment by InitialDet** [comment]
For now you can use this with triggernometry, just make sure to edit the keycodes with the key ur Cast is at.
[autocast.zip](https://github.com/InitialDet/AutoHook/files/8795320/autocast.zip)

**Comment by InitialDet** [comment]
Alright, I've added an option for Auto Cast/Mooch. I hope it's not too confusing for yall
